In [8]:
import numpy as np
import tsia
import pandas as pd
def _markov_transition_field(X_binned, X_mtm, n_timestamps):
    X_mtf = np.zeros((n_timestamps, n_timestamps))
    
    # We loop through each timestamp twice to build a N x N matrix:
    for i in range(n_timestamps):
        for j in range(n_timestamps):
            # We align each probability along the temporal order: MTF(i,j) 
            # denotes the transition probability of the bin 'i' to the bin 
            # 'j':
            X_mtf[i, j] = X_mtm[X_binned[i], X_binned[j]]
            
    return X_mtf

X = np.array([1, 7, 10, 5])

X_ = pd.DataFrame(X)
X_binned, bin_edges = tsia.markov.discretize(X_, 2)
print(X_binned+1)
X_mtm = tsia.markov.markov_transition_matrix(X_binned)
print(X_mtm)
X_mtm = tsia.markov.markov_transition_probabilities(X_mtm)
print(X_mtm)
X_mtf = _markov_transition_field(X_binned, X_mtm, len(X))
print(X_mtf)

[1 2 2 1]
[[0. 1.]
 [1. 1.]]
[[0.  1. ]
 [0.5 0.5]]
[[0.  1.  1.  0. ]
 [0.5 0.5 0.5 0.5]
 [0.5 0.5 0.5 0.5]
 [0.  1.  1.  0. ]]
